apiVersion: v1
kind: Service
metadata:
  name: lifo
spec:
  selector:
    app: lifo
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifo
  template:
    metadata:
      labels:
        app: lifo
    spec:
      containers:
        - name: lifo
          image: saransh98/lifo:1.0.3
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always